apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd # vagy argo, amit használsz az ArgoCD-nek
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 69.3.1 # Egy stabil verzió
    chart: kube-prometheus-stack
    helm:
      values: |
        # Itt tudjuk finomhangolni a beállításokat lokális környezetre
        grafana:
          service:
            type: LoadBalancer
        prometheus:
          prometheusSpec:
            retention: 1d
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # Egy külön tiszta névtér a monitorozásnak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Az ArgoCD magától létrehozza a 'monitoring' névteret
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true