apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homelab

# Beolvassuk a közös alapot ÉS a helyi titkosított jelszót is
resources:
- ../../base
- sealed-secret.yaml
- postgres-pvc.yaml

# Ezt a részt írja felül a GitHub Actions shared pipeline-ja
images:
- name: image_placeholder
  newName: daemia8702/homelab-app
  newTag: 0.0.9
