apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab
  namespace: homelab
  labels:
    app: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homelab
  template:
    metadata:
      labels:
        app: homelab
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: homelab
          image: image_placeholder
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATASOURCE
              value: jdbc:postgresql://db:5432/homelab
            - name: DB_USERNAME
              value: daemia
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cred
                  key: password
