name: shared-deploy.yml
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      GITOPS_TOKEN:
        required: true
jobs:
  update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

        with:
          token: ${{ secrets.GITOPS_TOKEN }}
          repository: daemia8702/homelab-ops
          ref: main
          clean: true
          fetch-depth: 0

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Clone and Update GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/daemia8702/homelab-ops.git ops-dir  
          cd ops-dir/overlays/minikube
        
          kustomize edit set image image_placeholder=daemia8702/${{ inputs.app_name }}:${{ inputs.image_tag }}
            
          git config user.name "GitOps [BOT]"
          git config user.email "gitops@company.com"
            
          git add kustomization.yaml
          git commit -m "Automated deploy: ${{ inputs.app_name }} to tag ${{ inputs.image_tag }}"
          git push origin main